# Generated by Django 2.0.6 on 2018-06-02 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('time', models.DateTimeField()),
                ('content', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bao_id', models.CharField(max_length=16)),
                ('palce', models.CharField(max_length=64)),
                ('human1_age', models.IntegerField()),
                ('human1_status', models.CharField(max_length=64)),
                ('human2_age', models.IntegerField()),
                ('human2_status', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=64)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户信息')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
