# Generated by Django 2.0.6 on 2018-06-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WenShi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_created=True)),
                ('Wendu', models.IntegerField()),
                ('Shidu', models.IntegerField()),
            ],
        ),
    ]
